// Typed view of the shared fixtures. The Rust MockBackend embeds the same JSON files.
import type { DominoConfig } from "../config/types";
import type { RawChangeHistory, RawIssue, RawLinkType, RawRemoteLink, RawStatusDef, RawUser } from "./jiraTypes";
import acme from "../../fixtures/mock/acme.json";
import partner from "../../fixtures/mock/partner.json";
import linkTypes from "../../fixtures/mock/linkTypes.json";
import config from "../../fixtures/mock/config.json";

export type MockSite = {
  /** Fixture dates are relative to this day ("YYYY-MM-DD"). */
  generatedOn?: string;
  issues: RawIssue[];
  remoteLinks: Record<string, RawRemoteLink[]>;
  /** Status changelogs keyed by Jira issue id. */
  changelogs?: Partial<Record<string, RawChangeHistory[]>>;
  statuses?: RawStatusDef[];
  /** `GET /myself` on this site. */
  myself?: RawUser;
};

// JSON imports widen string-literal unions (e.g. statusCategory.key) to `string`, so the fixtures can't be
// assigned to the Jira types directly; they are generated by scripts/gen-mock-fixtures.mjs in that exact shape.
export const mockSites: Record<string, MockSite> = {
  acme: acme as unknown as MockSite,
  partner: partner as unknown as MockSite,
};

export const mockLinkTypes: RawLinkType[] = linkTypes.issueLinkTypes;

export const mockConfig: DominoConfig = config as DominoConfig;
